### ISSUE TITLE
Typo in the name 

### ISSUE THREAD

**Issue by Lardpower** [Bandwidth/php-bandwidth-iris#34]
When you try to create a new instance of the `\Iris\Account` class with an empty second optional parameter `$client`, you will encounter the following error:

```
Uncaught Error: Class 'Iris\GuzzleClient' not found in /vendor/bandwidth/iris/src/RestEntry.php:16
--
  | Stack trace:
  | #0 /vendor/bandwidth/iris/src/Account.php(8): Iris\RestEntry->init(NULL, 'accounts')
  | #1 BandwidthService.php(180): Iris\Account->construct('MY_ACCOUNT_ID', NULL)

```

There is a typo in the name of the class `GuzzleClient`. Based on the parameters passed to such `GuzzleClient` constructor
```
// /vendor/bandwidth/iris/src/RestEntry.php:15

$this->client = new GuzzleClient(\Iris\Config::REST_LOGIN, \Iris\Config::REST_PASS, Array('url' => \Iris\Config::REST_URL));
```
it's obvious the the correct class name is `Client` that stands for `\Iris\iClient` class declared in `/bandwidth/iris/core/Client.php`.

The foregoing constructor also utilizes the `\Iris\Config` class that isn't defined anywhere except as a stub in the `vendor/bandwidth/iris/examples/config.php.example` file.

These problems aren't critical since I can initialize a new instance of the `\Iris\Account` class using non-empty second parameter, but still they can be easily fixed.

**Comment by menriquez** [comment]
maybe do a pull request to fix it?

**Comment by ajrice6713** [comment]
Fixed in v4.0.1
